### ISSUE TITLE
gebrekkige foutafhandeling

### ISSUE THREAD

**Issue by axd1967** [OnroerendErfgoed/skosprovider_atramhasis#58]
* afwezigheid van de key `uri` wordt niet goed opgevangen.
probleem bestaat al sinds tenminste 

[2019-06-09 22:42:35 +0000] [32596] [ERROR] Exception in worker process

```
supervisorctl restart inventaris

root@vioe-inventaris2-prod-1:~# tailf /var/log/inventaris/gunicorn.log

[2019-08-09 20:47:30 +0000] [28722] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/workers/gthread.py", line 109, in init_process
    super(ThreadWorker, self).init_process()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 63, in load
    return self.load_pasteapp()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 59, in load_pasteapp
    return load_pasteapp(self.cfgurl, self.relpath, global_conf=self.cfg.paste_global_conf)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/gunicorn/app/pasterapp.py", line 69, in load_pasteapp
    global_conf=global_conf)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 253, in loadapp
    return loadobj(APP, uri, name=name, **kw)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 278, in loadobj
    return context.create()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 209, in invoke
    app = context.app_context.create()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 715, in create
    return self.object_type.invoke(self)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/paste/deploy/loadwsgi.py", line 152, in invoke
    return fix_call(context.object, context.global_conf, **context.local_conf)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/paste/deploy/util.py", line 55, in fix_call
    val = callable(*args, **kw)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/__init__.py", line 146, in main
    config.include('inventaris.skos')
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/pyramid/config/__init__.py", line 676, in include
    c(configurator)
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/inventaris/skos/__init__.py", line 39, in includeme
    scheme_id='SOORTEN'
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/skosprovider_atramhasis/providers.py", line 49, in __init__
    concept_scheme = self._get_concept_scheme()
  File "/var/projects/inventaris/venv/local/lib/python2.7/site-packages/skosprovider_atramhasis/providers.py", line 282, in _get_concept_scheme
    response.json()['uri'],
KeyError: 'uri'
```

https://github.com/OnroerendErfgoed/skosprovider_atramhasis/blob/fc0900179c199afc90a0ae3883cd0278c573b013/skosprovider_atramhasis/providers.py#L279-L282

thesaurus:
```
2019-08-12 09:33:26,780 ERROR [thesaurus.exception_views][Thread-2] 'NoneType' object has no attribute 'rollback'
Traceback (most recent call last):
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 138, in _class_view
    response = getattr(inst, attr)()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/atramhasis/audit.py", line 65, in advice
    response = fn(parent_object, *args, **kw)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/atramhasis/views/crud.py", line 97, in get_conceptscheme
    return ProviderView(self.request).get_conceptscheme()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid_skosprovider/views.py", line 89, in get_conceptscheme
    'label': provider.concept_scheme.label(language).label if provider.concept_scheme.label(language) else None,
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 98, in concept_scheme
    return self._get_concept_scheme()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 282, in go
    parent_object.session.rollback()
AttributeError: 'NoneType' object has no attribute 'rollback'

2019-08-12 09:33:32,446 ERROR [thesaurus.exception_views][Thread-2] Transaction must be committed using the transaction manager
Traceback (most recent call last):
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 138, in _class_view
    response = getattr(inst, attr)()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/atramhasis/audit.py", line 65, in advice
    response = fn(parent_object, *args, **kw)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/atramhasis/views/crud.py", line 97, in get_conceptscheme
    return ProviderView(self.request).get_conceptscheme()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid_skosprovider/views.py", line 89, in get_conceptscheme
    'label': provider.concept_scheme.label(language).label if provider.concept_scheme.label(language) else None,
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 98, in concept_scheme
    return self._get_concept_scheme()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 279, in go
    parent_object.session.commit()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 943, in commit
    self.transaction.commit()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 467, in commit
    self._prepare_impl()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 436, in _prepare_impl
    self.session.dispatch.before_commit(self.session)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/event/attr.py", line 284, in __call__
    fn(*args, **kw)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/zope/sqlalchemy/datamanager.py", line 255, in before_commit
    "Transaction must be committed using the transaction manager"
AssertionError: Transaction must be committed using the transaction manager

2019-08-12 09:33:32,451 ERROR [thesaurus.exception_views][Thread-1] A transaction is already begun.  Use subtransactions=True to allow subtransactions.
Traceback (most recent call last):
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/tweens.py", line 39, in excview_tween
    response = handler(request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/router.py", line 156, in handle_request
    view_name
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/view.py", line 642, in _call_view
    response = view_callable(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 390, in attr_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 368, in predicate_wrapper
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 301, in secured_view
    return view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 439, in rendered_view
    result = view(context, request)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid/viewderivers.py", line 138, in _class_view
    response = getattr(inst, attr)()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/atramhasis/audit.py", line 65, in advice
    response = fn(parent_object, *args, **kw)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/atramhasis/views/crud.py", line 97, in get_conceptscheme
    return ProviderView(self.request).get_conceptscheme()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/pyramid_skosprovider/views.py", line 94, in get_conceptscheme
    'languages': provider.concept_scheme.languages
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/providers.py", line 98, in concept_scheme
    return self._get_concept_scheme()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/skosprovider_sqlalchemy/utils.py", line 286, in go
    parent_object.session.close()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1194, in close
    self._close_impl(invalidate=False)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1233, in _close_impl
    transaction.close(invalidate)
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 556, in close
    self.session.begin()
  File "/var/projects/thesaurus/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 857, in begin
    "A transaction is already begun.  Use "
InvalidRequestError: A transaction is already begun.  Use subtransactions=True to allow subtransactions.

```

smelly? 
* rollback foutmelding
* "A transaction is already begun.  Use subtransactions=True to allow subtransactions."

thx @Wim-De-Clercq

**Comment by koenedaele** [comment]
Da's het eeuwige probleem met thesaurus/atramhasis. Los daarvan is de foutafhandeling van skosprovider_atramhasis idd niet correct.

**Comment by axd1967** [comment]
ajjj... die bug is intussen tot in de UI bovengedreven: https://trac.onroerenderfgoed.be/toepassingen/ticket/2331
